version: '3'

services:
  corenlp:
    image: frnkenstien/corenlp
    ports:
      - "9000:9000"
    environment:
      - JAVA_XMX=1.5g
    deploy:
      replicas: 6
      resources:
          limits:
            memory: 1800M
