version: '3'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"

  corenlp:
    image: nlpbox/corenlp
    ports:
      - "9000:9000"
    environment:
      - JAVA_XMX=1500M
    deploy:
      replicas: 6
      resources:
          limits:
            memory: 1800M
